### ISSUE TITLE
Merge Projects

### ISSUE THREAD

**Issue by RandomString123** [RandomString123/FWF.jl#2]
@bkamins creating this issue so we can discuss without spamming the metadata repo.  

However, you might have a look at what I have implemented. Largely it is a much lighter approach but you could consider:

in your implementation you use byte indexing and I use character indexing - I recommend my approach - as I guess your will badly fail on UTF-8 encoded data;
adding something similar to keep keyword argument I have if field widths are passed (to allow for simple dropping of unwanted columns which often happen in FWF files - this is not needed with ranges version);
I guess I have a bit different handling of malformed data;
I have implemented auto detection of column widths which is handy in many situations.
Anyway - please let me know what you think how we could proceed as I think joining the efforts is the best approach!

**Comment by RandomString123** [comment]
> in your implementation you use byte indexing and I use character indexing - I recommend my approach - as I guess your will badly fail on UTF-8 encoded data;

My code does handle UTF-8 properly.  readcol() reads in via number of bytes and readline() reads in a whole line but parses based on number of bytes in a string, not the number of characters, using sizeof().  See test/io.jl line 69.

>adding something similar to keep keyword argument I have if field widths are passed (to allow for simple dropping of unwanted columns which often happen in FWF files - this is not needed with ranges version);

Agree completely that is great functionality!  One thing is, right now my code is assuming ranges are continuous so a slight modification will be needed. 

> I guess I have a bit different handling of malformed data;

My handling is to just drop a line that is not the correct length (That is the only testing I do).  I don't track which rows were malformed so my column based parsing just throws an exception if there were any malformed lines in the file.  My row based parsing just skips any row that is not the correct length.

> I have implemented auto detection of column widths which is handy in many situations.
I agree!  

As for the code feel free to change / refactor anything.   I copied a lot of the structure from CSV.jl which was a good base but I am not sure I like the use of an Options object as well as a Source.  I also think the Source constructor is getting a bit long.   It will also be great to merge our tests as you probably have a bunch of test cases I did not think of.

**Comment by bkamins** [comment]
Let us treat it peace by peace. The key issue is UTF-8.
How would you read the following data, which is in a proper FWF format under UTF-8 (columns are `1:1`, `3:3` and `5:5`):

```
α 1 x
a 2 y
∀ ∅ z
```

**Comment by RandomString123** [comment]
My US centrist view would mangle that example because I would assume the columns are 1:3,4:6,7:9 if they needed to contain a multi-byte character.   And the columns that don't contain multi-byte characters will get mangled if they are not padded appropriately.  

My code as it is assumes that the file is fixed width based on the number of bytes in the column.  So the presence of unicode means there is one less character available in a column per-unicode character it contains.  Thus a width 1 column with a unicode character in it will fail under my code.

I am looking at this from a perspective of reading in old COBOL files that were produced by a mainframe and based on a COLSPEC specification.   In this case the code needs to be able to handle both of these lines as if they were the same length because ÄĜË is 6 bytes but only 3 characters long.  
```
010182946NAME WITHHELD BY AGENCY19810331AA00#########35-39 04GS075-9   0318C015699810F1
010182946NAME WITHHELD BY ÄĜË19810331AA00#########35-39 04GS075-9   0318C015699810F1
```
Edit:  Forgot to state this example contains 18 columns of data.  The spec is contained in https://github.com/RandomString123/FWF.jl/blob/master/test/io.jl @ 87

Here is an issue opened against SPSS that describes the problem, maybe better?, http://www-01.ibm.com/support/docview.wss?uid=swg1PM87684 

I think we might need two different processing paths depending on what assumptions can be made about the data.  The easy solution is a flag...a hard solution is trying to figure out how to treat the file in an automated manner.

**Comment by RandomString123** [comment]
As an aside and something we might just want to let drop.

I always treated multi-byte characters as the current machine default byte order.   This is possibly the wrong thing to do as files like my example are typically exported from mainframes which are big-endian and produce multi-byte characters that are in reverse byte-order from what modern little-endian systems expect to find.

**Comment by bkamins** [comment]
Interesting about COBOL. As you probably can guess in France or Poland people would have a different perspective 😄.
E.g. http://www.oracle.com/webfolder/technetwork/data-quality/edqhelp/Content/introduction/getting_started/configuring_fixed_width_text_file_formats.htm says to count characters not bytes.

I think that adding a flag is a good idea as both options seem to be needed.

**Comment by RandomString123** [comment]
I agree, it just makes everything twice as difficult.  I guess that is why people use frameworks ;)

At least now we have a path forward.   

Also, they merged this repo into METADATA so we should be good to go from that aspect.

**Comment by RandomString123** [comment]
With the integration #3 I am going to close this.  I have opened issues for each of the items above plus some items that come up in discussions.
