### ISSUE TITLE
Handle malformed rows better

### ISSUE THREAD

**Issue by RandomString123** [RandomString123/FWF.jl#5]
The code just skips over malformed rows if a flag is provided.   Should think about alternate handling.

**Comment by bkamins** [comment]
We can have three behaviors:
1 throw error
2. ignore
3. parse as much as possible and treat the rest as empty string

Currently `skiponerror` handles option 1 or 2. We could rename it and allow option 3. Is this what seems reasonable? If yes I can implement it.

**Comment by RandomString123** [comment]
It sounds like a good path.  What would we do in this new case?

One reasonable path is filling the remaining columns with missing.  I can’t think of any others.

**Comment by RandomString123** [comment]
I think we are good with this as of #16
